### ISSUE TITLE
After save, files are forgotten when re-open page

### ISSUE THREAD

**Issue by jsblair9** [plainlanguage/Statamic-File-Clerk#2]
Hey so I noticed that when I added a bunch of files everything worked great initially. But after I saved left the page, and then came back to the page - the files were no longer present, but the remove button was still active. 
ie. didn't add all the files at once, and came back to add more but all the original files were "lost"

NB. - I've put file clerk in an inception Grid. Also on the initial save, everything works great and as it should.
## fieldset

```
fields:

 forms:
  type: grid
  fields:
    form_category:
      display: Form Category 
      instructions: This will be a tab that files will be filed under
      type: text
      width: 10%
    files:
      type: grid
      width: 90%
      fields:
        upload:
          type: fileclerk
          display: Uplaod the File to the Cloud
        file_name:
          type: text
```
## Screenshot of CP

![cp-lmd](https://cloud.githubusercontent.com/assets/4450975/4486991/f6752836-49f1-11e4-88d2-eda373e8650c.png)
