### ISSUE TITLE
Inline cascading array not workin

### ISSUE THREAD

**Issue by ncksnydr** [plainlanguage/Statamic-File-Clerk#3]
GENTLEMEN

I've found that I cannot cascade through a file clerk field type. I originally thought this was only when nested in a grid field type, but it appears that this is not working as expected in any instance. 
### Testing

```
work_images:
  - 
    image:
      - 
        url: http://capricious-cuckoo.s3.amazonaws.com/portfolio-images/bluebird-lg.jpg
        filename: bluebird-lg.jpg
        extension: jpg
        size: 55.74 KB
        size_bytes: 57076
        size_kilobytes: "55.74"
        size_megabytes: "0.05"
        size_gigabytes: "0.00"
        is_image: true
    caption: BlueBird Twitter Add-On for Statamic

```

Using the above example as a guide, the below example returns as null

```
{{ work_images }}
  {{ image:url }}
{{ /work_images }}
```

However, this _does_ work:

```
{{ work_images }}
  {{ image }} {{ url }} {{ /image }}
{{ /work_images }}
```

Again, the cascading returns null in both the grid and as a solo fieldtype (in my testing, at least). I'd be totally happy to help you fix this any way that I can. 

Thanks,
Smarf
